const routes = {
    home: '/',
    menu: '/menu',
    order: '/order',
    fogot: '/fogot',
    manage: '/manage',
    login: '/login',
    signup: '/signup',
    member: '/member',
    Table: '/Table',
    staff: '/staff',
    booking: '/booking',
    cart: '/cart',
    reset: '/reset',
    dashboard: '/dashboard',
    checkout: '/checkout',
    history: '/admin/history',
    contact: '/contact',
    voucher: '/voucher',
    billist: '/bills',
    hitry: '/history',
    detalbil: '/bills/:id',
    biifrom: '/bills/edit/:id',
    introduce: '/introduce',
    loginadmin: '/admin',
    billNow:'/billNow'
};
export default routes;
